/*
 * File: AddFileWindow.js
 * Date: Wed Mar 16 2011 10:33:45 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

AddFileWindow = Ext.extend(AddFileWindowUi, {
    initComponent: function() {
        AddFileWindow.superclass.initComponent.call(this);
        var addWindow = this;
        var pid = decodeURIComponent(window.location.pathname.split('/')[3]);
        var formPanel = this.get(0);
        var form = formPanel.getForm();
        var store = Ext.StoreMgr.lookup('Datastreams');
        var add = formPanel.buttons[0];
        add.addListener('click', function(button, event) {
            form.submit({
                url: '/adrbasic/ajax/addDatastream',
                params: {
                    pid: pid
                },
                success: function(form, action) {
                    var store = Ext.StoreMgr.lookup('Description');
                    store.reload(store.lastOptions);
                    store = Ext.StoreMgr.lookup('Datastreams');
                    store.reload(store.lastOptions);
                    store = Ext.StoreMgr.lookup('OverviewDatastreams');
                    store.reload(store.lastOptions);
                    addWindow.close();
                },
                failure: function(form, action) {
                    switch (action.failureType) {
                        case Ext.form.Action.CLIENT_INVALID:
                            Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
                            break;
                        case Ext.form.Action.CONNECT_FAILURE:
                            Ext.Msg.alert('Failure', 'Ajax communication failed');
                            break;
                        case Ext.form.Action.SERVER_INVALID:
                            Ext.Msg.alert('Failure', action.result.msg);
                    }
                }
            });
        });
    }
});
