/*
 * File: AddFileWindow.ui.js
 * Date: Wed Mar 16 2011 16:32:48 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

AddFileWindowUi = Ext.extend(Ext.Window, {
    title: 'Add File',
    width: 586,
    height: 209,
    layout: 'form',
    defaultType: 'form',
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                frame: true,
                headerAsText: false,
                hideBorders: true,
                animCollapse: false,
                height: 180,
                method: 'POST',
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'DSID',
                        anchor: '100%',
                        name: 'dsid'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        name: 'label'
                    },
                    {
                        xtype: 'combo',
                        fieldLabel: 'Control Group',
                        anchor: '100%',
                        name: 'control_group',
                        store: 'ControlGroups',
                        displayField: 'type',
                        typeAhead: true,
                        mode: 'local',
                        forceSelection: true
                    },
                    {
                        xtype: 'combo',
                        name: 'mime_type',
                        store: 'MIMETypes',
                        title: 'Mime Type',
                        fieldLabel: 'MIME Type',
                        forceSelection: true,
                        triggerAction: 'all',
                        displayField: 'mime',
                        typeAhead: true
                    },
                    {
                        xtype: 'checkbox',
                        fieldLabel: 'State',
                        boxLabel: 'Active',
                        anchor: '100%',
                        name: 'state'
                    }
                ],
                fbar: {
                    xtype: 'toolbar',
                    id: 'add-file-form-toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Add'
                        }
                    ]
                }
            }
        ];
        AddFileWindowUi.superclass.initComponent.call(this);
    }
});
