/*
 * File: AddFileWindow.ui.js
 * Date: Thu Mar 17 2011 16:48:12 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

AddFileWindowUi = Ext.extend(Ext.Window, {
    title: 'Add File',
    width: 586,
    height: 229,
    layout: 'anchor',
    defaultType: 'form',
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                frame: true,
                headerAsText: false,
                hideBorders: true,
                animCollapse: false,
                height: 220,
                method: 'POST',
                anchor: '100% 100%',
                autoHeight: true,
                fileUpload: true,
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'DSID',
                        anchor: '100%',
                        name: 'dsid',
                        allowBlank: false
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        name: 'label',
                        allowBlank: false
                    },
                    {
                        xtype: 'combo',
                        fieldLabel: 'Control Group',
                        anchor: '100%',
                        name: 'control_group',
                        store: 'ControlGroups',
                        displayField: 'type',
                        mode: 'local',
                        editable: false,
                        allowBlank: false,
                        triggerAction: 'all',
                        valueField: 'value',
                        submitValue: true
                    },
                    {
                        xtype: 'combo',
                        name: 'mime_type',
                        store: 'MIMETypes',
                        title: 'Mime Type',
                        fieldLabel: 'MIME Type',
                        triggerAction: 'all',
                        displayField: 'mime',
                        editable: false,
                        allowBlank: false
                    },
                    {
                        xtype: 'checkbox',
                        fieldLabel: 'State',
                        boxLabel: 'Active',
                        anchor: '100%',
                        name: 'state'
                    },
                    {
                        fieldLabel: 'Upload File',
                        xtype: 'fileuploadfield'
                    }
                ],
                fbar: {
                    xtype: 'toolbar',
                    autoHeight: true,
                    forceLayout: true,
                    height: 28,
                    id: 'add-file-form-toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Add'
                        }
                    ]
                }
            }
        ];
        AddFileWindowUi.superclass.initComponent.call(this);
    }
});
