/*
 * File: ADRBasicViewer.ui.js
 * Date: Mon Apr 11 2011 07:07:39 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ADRBasicViewerUi = Ext.extend(Ext.TabPanel, {
    activeTab: 2,
    width: 960,
    height: 920,
    layoutOnTabChange: true,
    border: false,
    forceLayout: true,
    id: 'adr-tabpanel',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Overview',
                layout: 'border',
                defaults: {
                    split: true,
                    
                },
                id: 'adr-overview-tab',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Description',
                        region: 'center',
                        autoLoad: {
                            url: '/adrbasic/ajax/getDescription',
                            
                        },
                        bodyStyle: '{\npadding: 15px\n}',
                        autoScroll: true,
                        id: 'adr-overview-description'
                    },
                    {
                        region: 'east',
                        collapseMode: 'standard',
                        collapsible: true,
                        xtype: 'filePanel'
                    }
                ]
            },
            {
                xtype: 'panel',
                title: 'Viewer',
                layout: 'border',
                defaults: {
                    split: true,
                    
                },
                id: 'adr-viewer-tab',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Viewer',
                        region: 'center',
                        id: 'adr-viewer-panel',
                        items: [
                            {
                                xtype: 'panel',
                                autoLoad: {
                                    url: "/adrbasic/ajax/getViewer",
                                    params: {
                                        pid: window.location.pathname.split('/')[
                                            3
                                        ]
                                    }
                                },
                                autoScroll: true,
                                boxMaxHeight: 885,
                                bodyStyle: 'max-height: 885px;',
                                id: 'adr-viewer'
                            }
                        ]
                    },
                    {
                        region: 'east',
                        collapsible: true,
                        collapseMode: 'standard',
                        xtype: 'filePanel'
                    }
                ]
            }
        ];
        ADRBasicViewerUi.superclass.initComponent.call(this);
    }
});
