/*
 * File: ADRBasicViewer.ui.js
 * Date: Thu Nov 17 2011 14:44:11 GMT-0400 (AST)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

/*
 * WARNING ... WARNING ... WARNING
 * 
 * This file has been edited by hand to resolve issues relating to Internet
 * Explorer and that browser's ability to handle mis-formed JavaScript.
 * 
 * There are places in this code where the generated Javascript leaves
 * trailing commas (,) at the end of lists.  IE will NOT parse these trailing
 * commas and cause the entire ADRBasicViewerUi object to be invalid.
 * 
 * Currently, there are three places where such trailing commas had to be
 * removed and they are commented in the code below.  If you change this
 * file using Extjs Designer then make sure that the trailing commas that it
 * generates are removed.
 * 
 * If you do not "diff" your files before checking in changes and (therefore)
 * miss this warning, as well as the warnings in the code below you are a
 * bad person and should be punished as such.
 */

ADRBasicViewerUi = Ext.extend(Ext.TabPanel, {
    activeTab: 0,
    width: 960,
    height: 970,
    layoutOnTabChange: true,
    border: false,
    forceLayout: true,
    id: 'adr-tabpanel',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Overview',
                layout: 'border',
                defaults: {
            	    // this line was edited by hand to remove a trailing comma
                    split: true
                },
                id: 'adr-overview-tab',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Description',
                        region: 'center',
                        autoLoad: {
                	        // this line was edited by hand to remove a trailing comma
                            url: '/adrbasic/ajax/getDescription'
                        },
                        bodyStyle: '{\npadding: 15px\n}',
                        autoScroll: true,
                        frame: true,
                        id: 'adr-overview-description'
                    },
                    {
                        region: 'east',
                        collapseMode: 'standard',
                        collapsible: true,
                        id: 'adr-overview-files',
                        xtype: 'filePanel'
                    }
                ]
            },
            {
                xtype: 'panel',
                title: 'Viewer',
                layout: 'border',
                defaults: {
        	        // this line was edited by hand to remove a trailing comma
                    split: true
                },
                id: 'adr-viewer-tab',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Viewer',
                        region: 'center',
                        autoLoad: {
                            url: "/adrbasic/ajax/getViewer",
                            params: {
                                pid: decodeURIComponent(window.location.pathname.split('/')[
                                    3
                                ])
                            }
                        },
                        frame: true,
                        autoScroll: true,
                        id: 'adr-viewer'
                    },
                    {
                        region: 'east',
                        collapsible: true,
                        collapseMode: 'standard',
                        id: 'adr-viewer-files',
                        xtype: 'filePanel'
                    }
                ]
            }
        ];
        ADRBasicViewerUi.superclass.initComponent.call(this);
    }
});
