/*
 * File: ControlGroups.js
 * Date: Thu Mar 17 2011 08:50:12 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ControlGroups = Ext.extend(Ext.data.ArrayStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        ControlGroups.superclass.constructor.call(this, Ext.apply({
            storeId: 'ControlGroups',
            data: [
                [
                    "Inline XML (X)"
                ],
                [
                    "Managed Resource (M)"
                ],
                [
                    "Redirect (R)"
                ],
                [
                    "External Reference (E)"
                ]
            ],
            fields: [
                {
                    name: 'type',
                    type: 'string'
                }
            ]
        }, cfg));
    }
});
new ControlGroups();