/*
 * File: Datastreams.js
 * Date: Tue Mar 15 2011 11:11:50 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Datastreams = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        Datastreams.superclass.constructor.call(this, Ext.apply({
            storeId: 'Datastreams',
            autoLoad: true,
            url: 'fedora/repository/ajax/getDatastreams',
            fields: [
                {
                    name: 'dsid'
                },
                {
                    name: 'label'
                },
                {
                    name: 'img'
                },
                {
                    name: 'mime'
                }
            ]
        }, cfg));
    }
});
new Datastreams();