/*
 * File: DeleteObjectWindow.ui.js
 * Date: Wed Mar 16 2011 17:12:35 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

DeleteObjectWindowUi = Ext.extend(Ext.Window, {
    title: 'My Window',
    width: 400,
    height: 250,
    initComponent: function() {
        DeleteObjectWindowUi.superclass.initComponent.call(this);
    }
});
