/*
 * File: DeleteObjectWindow.ui.js
 * Date: Thu Mar 17 2011 16:48:12 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

DeleteObjectWindowUi = Ext.extend(Ext.Window, {
    title: 'My Window',
    width: 400,
    height: 250,
    initComponent: function() {
        DeleteObjectWindowUi.superclass.initComponent.call(this);
    }
});
