/*
 * File: Description.js
 * Date: Tue Mar 15 2011 11:11:50 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Description = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        Description.superclass.constructor.call(this, Ext.apply({
            storeId: 'Description',
            fields: [
                {
                    name: 'title'
                },
                {
                    name: 'author'
                },
                {
                    name: 'description'
                }
            ]
        }, cfg));
    }
});
new Description();