/*
 * File: EditObjectWindow.ui.js
 * Date: Thu Mar 17 2011 08:46:14 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

EditObjectWindowUi = Ext.extend(Ext.Window, {
    title: 'My Window',
    width: 400,
    height: 250,
    initComponent: function() {
        EditObjectWindowUi.superclass.initComponent.call(this);
    }
});
