/*
 * File: EditFilesPanel.ui.js
 * Date: Wed Mar 16 2011 16:39:12 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

EditFilesPanelUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Manage Files',
    bodyStyle: 'background-color:#FFFFFF;',
    preventBodyReset: true,
    initComponent: function() {
        this.defaults = {
            frame: false,
            padding: 0,
            border: false
        };
        this.fbar = {
            xtype: 'toolbar',
            id: 'edit-files-panel-toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Add',
                    scale: 'large',
                    width: 75
                },
                {
                    xtype: 'button',
                    text: 'Replace',
                    width: 75,
                    scale: 'large'
                },
                {
                    xtype: 'button',
                    text: 'Delete',
                    width: 75,
                    scale: 'large'
                }
            ]
        };
        this.items = [
            {
                xtype: 'dataview',
                itemSelector: 'div',
                store: 'Datastreams',
                tpl: '<tpl for="."><div class="adr-edit-file-img-block"><img src=\'{img_url}\' title=\'label\' class="adr-edit-file-img"><div class="adr-edit-file-label">{dsid}</div></div></tpl>',
                overClass: 'x-view-over',
                singleSelect: true,
                trackOver: true,
                id: 'edit-files-panel-data-viewer'
            }
        ];
        EditFilesPanelUi.superclass.initComponent.call(this);
    }
});
