/*
 * File: EditObjectPanel.js
 * Date: Mon Mar 07 2011 02:10:59 GMT-0600 (CST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

EditObjectPanel = Ext.extend(EditObjectPanelUi, {
    initComponent: function() {
        EditObjectPanel.superclass.initComponent.call(this);
        var edit = this.buttons[0];
        var permissions = this.buttons[1];
        var remove = this.buttons[2];
        edit.addListener('click', function(button, event) {
            var window = new EditObjectWindow();
            window.show(this);
        });
        permissions.addListener('click', function(button, event) {
            Ext.Msg.alert('Failure', 'This will redirect to the XCAML form, once its available.');
        });
    }
});
Ext.reg('editobjectpanel', EditObjectPanel);