/*
 * File: EditObjectPanel.js
 * Date: Mon Mar 07 2011 02:10:59 GMT-0600 (CST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

EditObjectPanel = Ext.extend(EditObjectPanelUi, {
    initComponent: function() {
        EditObjectPanel.superclass.initComponent.call(this);
    }
});
Ext.reg('editobjectpanel', EditObjectPanel);