/*
 * File: EditFileWindow.ui.js
 * Date: Thu Mar 17 2011 11:23:50 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

EditFileWindowUi = Ext.extend(Ext.Window, {
    title: 'My Window',
    width: 400,
    height: 250,
    initComponent: function() {
        EditFileWindowUi.superclass.initComponent.call(this);
    }
});
