/*
 * File: EditObjectWindow.js
 * Date: Wed Mar 16 2011 10:33:45 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

EditObjectWindow = Ext.extend(EditObjectWindowUi, {
    initComponent: function() {
        EditObjectWindow.superclass.initComponent.call(this);
    }
});
