/*
 * File: EditDescriptionPanel.ui.js
 * Date: Tue Mar 15 2011 11:11:50 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

EditDescriptionPanelUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edit Description',
    hideBorders: true,
    frame: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Title',
                anchor: '100%',
                name: 'title'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Author',
                anchor: '100%',
                name: 'author'
            },
            {
                xtype: 'textarea',
                anchor: '100%',
                fieldLabel: 'Description',
                height: 109,
                name: 'description'
            }
        ];
        this.fbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    text: 'Reset'
                }
            ]
        };
        EditDescriptionPanelUi.superclass.initComponent.call(this);
    }
});
