/*
 * File: EditObjectPanel.js
 * Date: Mon Mar 07 2011 02:10:59 GMT-0600 (CST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

EditObjectPanel = Ext.extend(EditObjectPanelUi, {
    initComponent: function() {
        EditObjectPanel.superclass.initComponent.call(this);
        var edit = this.buttons[0];
        var permissions = this.buttons[1];
        var remove = this.buttons[2];
        edit.addListener('click', function(button, event) {
            var window = new EditObjectWindow();
            window.show(this);
        });
        permissions.addListener('click', function(button, event) {
            Ext.Msg.alert('Failure', 'This will redirect to the XCAML form, once its available.');
        });
        remove.addListener('click', function(button, event) {
            Ext.Msg.confirm('Delete', 'Are you sure you want to delete this Object?', function(btn, text){
                if (btn == 'yes') {
                    var pid = window.location.pathname.split('/')[3];
                    Ext.Ajax.request({
                        url: '/adrbasic/ajax/deleteObject',
                        success: function(response, opts) {
                            var obj = Ext.decode(response.responseText);
                            if(obj.success) {
                                // Redirect to top collection for now.
                                var location = window.location;
                                var page = location.protocol + '//' + location.host + '/fedora/repository/';
                                window.location = page;
                            }
                            else {
                                Ext.Msg.alert('Failure', obj.msg);
                            }
                            
                        },
                        failure: function(response, opts) {
                            Ext.Msg.alert('Failure', 'Failed to Delete Object.');
                        },
                        params: {
                            pid: pid
                        }
                    });

                }
            });
        });
    }
});
Ext.reg('editobjectpanel', EditObjectPanel);