/*
 * File: EditFileWindow.ui.js
 * Date: Wed Mar 16 2011 16:39:12 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

EditFileWindowUi = Ext.extend(Ext.Window, {
    title: 'My Window',
    width: 400,
    height: 250,
    initComponent: function() {
        EditFileWindowUi.superclass.initComponent.call(this);
    }
});
