/*
 * File: EditFilesPanel.js
 * Date: Mon Mar 07 2011 02:10:59 GMT-0600 (CST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

EditFilesPanel = Ext.extend(EditFilesPanelUi, {
    initComponent: function() {
        EditFilesPanel.superclass.initComponent.call(this);
        var viewer = this.get('edit-files-panel-data-viewer');
        var add = this.buttons[0];
        var replace = this.buttons[1];
        var remove = this.buttons[2];
        add.addListener('click', function(button, event) {
            var window = new AddFileWindow();
            window.show(this);
        });
    }
});
Ext.reg('editfilespanel', EditFilesPanel);