/*
 * File: EditDescriptionPanel.ui.js
 * Date: Tue Mar 15 2011 18:42:08 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

EditDescriptionPanelUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edit Description',
    hideBorders: true,
    frame: true,
    standardSubmit: true,
    method: 'POST',
    id: 'edit-description-form',
    initComponent: function() {
        this.initialConfig = Ext.apply({
            standardSubmit: true,
            method: 'POST'
        }, this.initialConfig);
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Title',
                anchor: '100%',
                name: 'title',
                emptyText: 'Title'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Author',
                anchor: '100%',
                name: 'author',
                emptyText: 'Author'
            },
            {
                xtype: 'textarea',
                anchor: '100%',
                fieldLabel: 'Description',
                height: 109,
                name: 'description',
                emptyText: 'Description'
            }
        ];
        this.fbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    text: 'Reset'
                }
            ]
        };
        EditDescriptionPanelUi.superclass.initComponent.call(this);
    }
});
