/*
 * File: FilePanel.js
 * Date: Mon Apr 04 2011 14:43:12 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

FilePanel = Ext.extend(FilePanelUi, {
    initComponent: function() {
        FilePanel.superclass.initComponent.call(this);
    }
});
Ext.reg('filePanel', FilePanel);