/*
 * File: FileUploadField.ui.js
 * Date: Thu Mar 17 2011 08:50:12 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

FileUploadFieldUi = Ext.extend(Ext.form.TextField, {
    initComponent: function() {
        FileUploadFieldUi.superclass.initComponent.call(this);
    }
});
