/*
 * File: FileUploadField.ui.js
 * Date: Thu Mar 17 2011 12:41:21 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

FileUploadFieldUi = Ext.extend(Ext.form.TextField, {
    initComponent: function() {
        FileUploadFieldUi.superclass.initComponent.call(this);
    }
});
