/*
 * File: ManagePanel.ui.js
 * Date: Thu Mar 17 2011 11:23:50 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ManagePanelUi = Ext.extend(Ext.Panel, {
    title: 'Manage',
    layout: 'table',
    defaults: '',
    defaultType: 'auto',
    frame: true,
    autoHeight: true,
    initComponent: function() {
        this.layoutConfig = {
            columns: 1
        };
        this.items = [
            {
                flex: 1,
                margins: '0 0 10 0',
                xtype: 'editobjectpanel'
            },
            {
                flex: 2,
                margins: '0 0 10 0',
                xtype: 'editdescriptionpanel'
            },
            {
                flex: 4,
                margins: '0 0 5 0',
                xtype: 'editfilespanel'
            }
        ];
        ManagePanelUi.superclass.initComponent.call(this);
    }
});
