/*
 * File: ManagePanel.ui.js
 * Date: Tue Apr 05 2011 10:48:58 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ManagePanelUi = Ext.extend(Ext.Panel, {
    title: 'Manage',
    initComponent: function() {
        this.items = [
            {
                xtype: 'editobjectpanel'
            },
            {
                xtype: 'editfilespanel'
            }
        ];
        ManagePanelUi.superclass.initComponent.call(this);
    }
});
