/*
 * File: MyDataView.js
 * Date: Tue Apr 05 2011 11:19:14 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MyDataView = Ext.extend(MyDataViewUi, {
    initComponent: function() {
        MyDataView.superclass.initComponent.call(this);
    }
});
Ext.reg('mydataview', MyDataView);