/*
 * File: MyDataView.ui.js
 * Date: Tue Apr 05 2011 11:19:14 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyDataViewUi = Ext.extend(Ext.DataView, {
    itemSelector: 'div .adr-edit-file-img-block',
    store: 'Datastreams',
    overClass: 'x-view-over',
    singleSelect: true,
    trackOver: true,
    id: 'adr-manage-files-data-viewer',
    initComponent: function() {
        this.tpl = [
            '<tpl for=".">',
            '<div class="adr-edit-file">',
            '<div class="adr-edit-file-label">{[fm.ellipsis(values.label, 30, true)]}</div>',
            '<img src=\'{img_url}\' title=\'label\' class="adr-edit-file-img">',
            '<div class="adr-edit-file-label">{[fm.ellipsis(values.dsid, 30, true)]}</div>',
            '</div>',
            '</tpl>'
        ];
        MyDataViewUi.superclass.initComponent.call(this);
    }
});
