/*
 * File: MyTabPanel1.ui.js
 * Date: Mon Apr 04 2011 14:37:24 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyTabPanel1Ui = Ext.extend(Ext.TabPanel, {
    activeTab: 0,
    width: 400,
    height: 250,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Tab 1'
            },
            {
                xtype: 'panel',
                title: 'Tab 2'
            },
            {
                xtype: 'panel',
                title: 'Tab 3'
            }
        ];
        MyTabPanel1Ui.superclass.initComponent.call(this);
    }
});
