/*
 * File: MyTabPanel1.js
 * Date: Mon Apr 04 2011 13:25:04 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MyTabPanel1 = Ext.extend(MyTabPanel1Ui, {
    initComponent: function() {
        MyTabPanel1.superclass.initComponent.call(this);
    }
});
