/*
 * File: OverviewPanel.ui.js
 * Date: Fri Mar 18 2011 13:12:53 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

OverviewPanelUi = Ext.extend(Ext.Panel, {
    title: 'Overview',
    layout: 'table',
    frame: true,
    preventBodyReset: true,
    autoHeight: true,
    defaults: '{ padding: 0px }',
    initComponent: function() {
        this.layoutConfig = {
            columns: 2
        };
        this.items = [
            {
                flex: 1,
                layout: 'table',
                columnWidth: 0.6,
                cellId: 'adr-overview-description-cell',
                colspan: 1,
                rowspan: 1,
                xtype: 'descriptionpanel'
            },
            {
                columnWidth: 0.19,
                layout: 'table',
                cellId: 'adr-overview-files-cell',
                colspan: 1,
                rowspan: 1,
                xtype: 'filespanel'
            }
        ];
        OverviewPanelUi.superclass.initComponent.call(this);
    }
});
