/*
 * File: xds_index.js
 * Date: Mon Apr 04 2011 14:37:24 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new ADRBasicViewer({
        renderTo: Ext.getBody()
    });
    cmp1.show();
    var cmp2 = new OverviewPanel({
        renderTo: Ext.getBody()
    });
    cmp2.show();
    var cmp3 = new ManagePanel({
        renderTo: Ext.getBody()
    });
    cmp3.show();
    var cmp4 = new AddFileWindow({
        renderTo: Ext.getBody()
    });
    cmp4.show();
    var cmp5 = new ReplaceFileWindow({
        renderTo: Ext.getBody()
    });
    cmp5.show();
    var cmp6 = new EditObjectWindow({
        renderTo: Ext.getBody()
    });
    cmp6.show();
    var cmp7 = new MyTabPanel1({
        renderTo: Ext.getBody()
    });
    cmp7.show();
});
