/*
 * File: xds_index.js
 * Date: Fri Mar 18 2011 13:12:53 GMT-0300 (ADT)
 * 
 * This file was generated by Ext Designer version 1.1.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new ADRBasicViewer({
        renderTo: Ext.getBody()
    });
    cmp1.show();
    var cmp2 = new EditDescriptionPanel({
        renderTo: Ext.getBody()
    });
    cmp2.show();
    var cmp3 = new AddFileWindow({
        renderTo: Ext.getBody()
    });
    cmp3.show();
    var cmp4 = new ReplaceFileWindow({
        renderTo: Ext.getBody()
    });
    cmp4.show();
});
