<?php

// $Id$

/**
 * @file
 *
 */
function adr_basic_viewer_menu() {
  $items = array();

  $items['adrbasic/ajax/getObjectProperties'] = array(
    'page callback' => 'adr_basic_viewer_get_object_properties',
    'access arguments' => array('view detailed list of content'),
    'type' => MENU_CALLBACK,
  );

  $items['adrbasic/ajax/setObjectProperties'] = array(
    'page callback' => 'adr_basic_viewer_set_object_properties',
    'access arguments' => array('edit fedora meta data'),
    'type' => MENU_CALLBACK,
  );

  $items['adrbasic/ajax/deleteObject'] = array(
    'page callback' => 'adr_basic_viewer_delete_object',
    'access arguments' => array('edit fedora meta data'),
    'type' => MENU_CALLBACK,
  );

  $items['adrbasic/ajax/getDatastreams'] = array(
    'page callback' => 'adr_basic_viewer_get_datastreams',
    'access arguments' => array('view detailed list of content'),
    'type' => MENU_CALLBACK,
  );

  $items['adrbasic/ajax/addDatastream'] = array(
    'page callback' => 'adr_basic_viewer_add_datastream',
    'access arguments' => array('add fedora datastreams'),
    'access callback' => 'user_access',
    'type' => MENU_CALLBACK,
  );
  $items['adrbasic/ajax/removeDatastream'] = array(
    'page callback' => 'adr_basic_viewer_remove_datastream',
    'access arguments' => array('purge objects and datastreams'),
    'access callback' => 'user_access',
    'type' => MENU_CALLBACK,
  );

  $items['adrbasic/ajax/getOverviewDatastreams'] = array(
    'page callback' => 'adr_basic_viewer_get_overview_datastreams',
    'access arguments' => array('view detailed list of content'),
    'type' => MENU_CALLBACK,
  );

  $items['adrbasic/ajax/getDescription'] = array(
    'page callback' => 'adr_basic_viewer_get_description',
    'access arguments' => array('view detailed list of content'),
    'type' => MENU_CALLBACK,
  );
  $items['adrbasic/ajax/getViewer'] = array(
    'page callback' => 'adr_basic_viewer_get_viewer',
    'access arguments' => array('view detailed list of content'),
    'type' => MENU_CALLBACK,
  );
  $items['adrbasic/ajax/getAllowedMIMETypes'] = array(
    'page callback' => 'adr_basic_viewer_get_allowed_mime_types',
    'access arguments' => array('add fedora datastreams'),
    'access callback' => 'user_access',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function adr_basic_viewer_get_pid() {
  $pid = $_REQUEST['pid'];
  $pid = urldecode($pid);
  return $pid;
}

/**
 *
 */
function adr_basic_viewer_get_description() {
  $pid = adr_basic_viewer_get_pid();
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'AjaxHandler');
    $handler = new AjaxHandler($pid);
    $reponse = $handler->getDescription();
    echo $reponse;
  }
}

/**
 * 
 */
function adr_basic_viewer_get_datastreams() {
  $pid = adr_basic_viewer_get_pid();
  $start = isset($_REQUEST['start']) ? $_REQUEST['start'] : 0;
  $limit = isset($_REQUEST['limit']) ? $_REQUEST['limit'] : 33;
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'AjaxHandler');
    $handler = new AjaxHandler($pid);
    $reponse = $handler->getDatastreams($start, $limit);
    echo json_encode($reponse);
  }
}

/**
 *
 */
function adr_basic_viewer_get_overview_datastreams() {
  $pid = adr_basic_viewer_get_pid();
  $start = isset($_REQUEST['start']) ? $_REQUEST['start'] : 0;
  $limit = isset($_REQUEST['limit']) ? $_REQUEST['limit'] : 5;
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'AjaxHandler');
    $handler = new AjaxHandler($pid);
    $reponse = $handler->getOverviewDatastreams($start, $limit);
    echo json_encode($reponse);
  }
}

/**
 * 
 */
function adr_basic_viewer_get_viewer() {
  $pid = adr_basic_viewer_get_pid();
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'ADRBasicViewer');
    $dsid = isset($_REQUEST['dsid']) ? $_REQUEST['dsid'] : NULL;
    $viewer = new ADRBasicViewer($pid, $dsid);
    echo $viewer->getViewer();
  }
}

/**
 * 
 */
function adr_basic_viewer_add_datastream() {
  $pid = adr_basic_viewer_get_pid();
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'AjaxHandler');
    $handler = new AjaxHandler($pid);
    $reponse = $handler->addDatastream($_POST);
    echo json_encode($reponse);
  }
}

/**
 * 
 */
function adr_basic_viewer_remove_datastream() {
  $pid = adr_basic_viewer_get_pid();
  $dsid = $_REQUEST['dsid'];
  if (isset($pid) && isset($dsid)) {
    module_load_include('inc', 'adr_basic_viewer', 'AjaxHandler');
    $handler = new AjaxHandler($pid);
    $reponse = $handler->deleteDatastream($dsid);
    echo json_encode($reponse);
  }
}

/**
 * Ajax request to get the allowed mime types for datastreams as defined by this fedora object's content model.
 *
 * Responds with a JSON object describing success or failure, and the allowed MIME Types for datastreams.
 *
 * Example: { success: true, msg: 'message', data: '{ { mime: 'image/jpg'}, ... }' }
 */
function adr_basic_viewer_get_allowed_mime_types() {
  $pid = adr_basic_viewer_get_pid();
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'AjaxHandler');
    $handler = new AjaxHandler($pid);
    $reponse = $handler->getAllowedMIMETypes();
    echo json_encode($reponse);
  }
}

/**
 * Ajax request to get the properties of an fedora object.
 *
 * Responds with a JSON object describing success or failure, and the objects
 * properties.
 *
 * Example: { success: true, msg: 'message', data: '{ { label: ''}, ... }' }
 */
function adr_basic_viewer_get_object_properties() {
  $pid = adr_basic_viewer_get_pid();
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'AjaxHandler');
    $handler = new AjaxHandler($pid);
    $reponse = $handler->getObjectProperties();
    echo json_encode($reponse);
  }
}

/**
 * Ajax request to set the properties of an fedora object.
 *
 * Responds with a JSON object describing success or failure, and the objects
 * properties.
 *
 * Example: { success: true, msg: 'message', data: '{ { label: ''}, ... }' }
 */
function adr_basic_viewer_set_object_properties() {
  $pid = adr_basic_viewer_get_pid();
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'AjaxHandler');
    $handler = new AjaxHandler($pid);
    $response = $handler->setObjectProperties($_POST);
    echo json_encode($response);
  }
}

/**
 * Ajax request to delete a fedora object.
 *
 * Responds with a JSON object describing success or failure.
 *
 * Example: { success: true, msg: 'message' }
 */
function adr_basic_viewer_delete_object() {
  $pid = adr_basic_viewer_get_pid();
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'AjaxHandler');
    $handler = new AjaxHandler($pid);
    $response = $handler->deleteObject();
    echo json_encode($response);
  }
}
