<?php

// $Id$

/**
 * @file
 *
 */
function adr_basic_viewer_menu() {
  $items = array();
  $items['adrbasic/ajax/getDatastreams'] = array(
    'page callback' => 'adr_basic_viewer_get_datastreams',
    'access arguments' => array('view detailed list of content'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['adrbasic/ajax/getOverviewDatastreams'] = array(
    'page callback' => 'adr_basic_viewer_get_overview_datastreams',
    'access arguments' => array('view detailed list of content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['adrbasic/ajax/getDescription'] = array(
    'page callback' => 'adr_basic_viewer_get_description',
    'access arguments' => array('view detailed list of content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['adrbasic/ajax/setDescription'] = array(
    'page callback' => 'adr_basic_viewer_set_description',
    'access arguments' => array('edit fedora meta data'),
    'access callback' => 'user_access',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['adrbasic/ajax/getViewer'] = array(
    'page callback' => 'adr_basic_viewer_get_viewer',
    'access arguments' => array('view detailed list of content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['adrbasic/ajax/addDatastream'] = array(
    'page callback' => 'adr_basic_viewer_add_datastream',
    'access arguments' => array('add fedora datastreams'),
    'access callback' => 'user_access',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['adrbasic/ajax/removeDatastream'] = array(
    'page callback' => 'adr_basic_viewer_remove_datastream',
    'access arguments' => array('purge objects and datastreams'),
    'access callback' => 'user_access',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['adrbasic/ajax/getAllowedMIMETypes'] = array(
    'page callback' => 'adr_basic_viewer_get_allowed_mime_types',
    'access arguments' => array('add fedora datastreams'),
    'access callback' => 'user_access',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function adr_basic_viewer_get_description() {
  $pid = $_REQUEST['pid'];
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'ADRBasic');
    $viewer = new ADRBasic($pid);
    $response = $viewer->getDescriptionAjaxResponse();
    echo $response;
  }
}

function adr_basic_viewer_set_description() {
  $pid = $_REQUEST['pid'];
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'ADRBasic');
    $viewer = new ADRBasic($pid);
    $response = $viewer->setDescriptionAjaxRequest();
    echo $response;
  }
}

function adr_basic_viewer_get_datastreams() {
  $pid = $_REQUEST['pid'];
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'ADRBasic');
    $viewer = new ADRBasic($pid);
    $response = $viewer->getDatastreamsAjaxResponse();
    echo $response;
  }
}

function adr_basic_viewer_get_overview_datastreams() {
  $pid = $_REQUEST['pid'];
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'ADRBasic');
    $viewer = new ADRBasic($pid);
    $response = $viewer->getOverviewDatastreamsAjaxResponse();
    echo $response;
  }
}

function adr_basic_viewer_get_viewer() {
  $pid = $_REQUEST['pid'];
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'ADRBasicViewer');
    $dsid = isset($_REQUEST['dsid']) ? $_REQUEST['dsid'] : NULL;
    $viewer = new ADRBasicViewer($pid, $dsid);
    echo $viewer->getViewer();
  }
}

function adr_basic_viewer_add_datastream() {
  $pid = $_REQUEST['pid'];
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'ADRBasic');
    $viewer = new ADRBasic($pid);
    echo $viewer->addDatastreamAjaxRequest();
  }
}

function adr_basic_viewer_remove_datastream() {
  $pid = $_REQUEST['pid'];
  if (isset($pid)) {

  }
}

function adr_basic_viewer_get_allowed_mime_types() {
  $pid = $_REQUEST['pid'];
  if (isset($pid)) {
    module_load_include('inc', 'adr_basic_viewer', 'ADRBasic');
    $viewer = new ADRBasic($pid);
    $response = $viewer->getAllowedMIMETypesAjaxResponse();
    echo $response;
  }
}